stages:
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ranche-test
      pushRemote: true
      registry: 127.0.0.1:34482
timeout: 60
