stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:1.10.7
      shellScript: |-
        mkdir -p /go/src
        ln -s `pwd` /go/src/rancher
        RUN set -ex &&  cd /go/src/rancher && CGO_ENABLED=0 go build -v -a -ldflags '-extldflags "-static"' -o rancher-test
        go test -cover
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rancher-test:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.10.8.23:5000
timeout: 60
