stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:1.10.7
      shellScript: |-
        mkdir -p /etc/docker/certs.d/slg.registry.com
        cp certs/domain.crt /etc/docker/certs.d/slg.registry.com/ca.crt
        echo “10.10.8.23 slg.registry.com” >> /etc/hosts
timeout: 60
