stages:
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ranche-test
      pushRemote: true
      registry: 10.10.8.23:5000
timeout: 60
