kind: Service
apiVersion: v1
metadata:
  name: ranchertest-service
spec:
  selector:
    app: rancher-test
  type: NodePort
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8087
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-ranchertest
  labels:
    app: rancher-test
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: rancher-test
  template:
    metadata:
      labels:
        app: rancher-test
    spec:
      imagePullSecrets:
      - name: slg-registry
      containers:
      - name: rancher-test
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8088
          hostPort: 7088
